### ISSUE TITLE
Unable to restore zip file. 

### ISSUE THREAD

**Issue by rcannon** [gendetection/UnbiasedGenImage#1]
Hi there!

I am trying to download the dataset, but when I attempt to `cat` the files together, I get a corrupted zip file. Looking though the list of files, it seems that there is one missing: there should be a `GenImage.zip` file along with all the `GenImage.zXYZ` ones. 

This [post](https://superuser.com/a/336224) might be helpful for creating zip archives. 

Thanks!

**Comment by gendetection** [comment]
Hey! 

 We just split the zip file using the following command (which is another popular method):
 
 `split -d -n 500 GenImage.zip GenImage.z`

so you can restore the full zip like this (as shown in the tutorial): 

`cat GenImage.z* > ../GenImage_restored.zip` 

This method should work fine and we tested it multiple times. Have you already tried this?

**Comment by rcannon** [comment]
Oh I didn't realize it was split with the `split` command. I assumed it was through `zip -s`. My bad. In that case we can probably close the issue; I'll reopen if there are further problems. Thanks!
